config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :sales
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static#index"
end

app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
   Copyrights Gem Automotive ©2018
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="index.html" class="site_title"><i class="fa fa-motorcycle"></i> <span>Gem AutoMotive LLP!</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_info">
    <span>Welcome,</span>
    <h2><%= current_user.name if current_user %></h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <ul class="nav side-menu">
      <li><a href="<%= sales_path %>"><i class="fa fa-balance-scale"></i> Sales</a></li>
      <li><a href="<%= customers_path %>"><i class="fa fa-male"></i> Customers</a></li>     
    </ul>
  </div>
</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <img src="images/img.jpg" alt=""><%= current_user.name %>
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li><a href="javascript:;"> Profile</a></li>
      <li>
        <a href="javascript:;">
          <span class="badge bg-red pull-right">50%</span>
          <span>Settings</span>
        </a>
      </li>
      <li><a href="javascript:;">Help</a></li>
      <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
    </ul>
  </li>

  <li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
      <i class="fa fa-envelope-o"></i>
      <span class="badge bg-green">6</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <div class="text-center">
          <a>
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </li>
    </ul>
  </li>
</ul>