config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :sales
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static#index"
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id           :integer          not null, primary key
#  name         :string
#  mobile       :string
#  show_room_id :integer
#  id_type      :string
#  id_number    :string
#  city         :string
#  address      :text
#  pin          :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Customer < ApplicationRecord
  belongs_to :show_room
  phony_normalize :mobile, default_country_code: 'IN'
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
	before_action :authenticate_user!

  def index
    @customers = Customer.where(show_room_id: current_user.show_room_id)

    respond_to do |format|
      format.html 
      format.json { render json: @customers }
    end
  end

  # # GET /customers/1
  # # GET /customers/1.json
  # def show
  #   @customer = customer.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @customer }
  #   end
  # end

  # # GET /customers/new
  # # GET /customers/new.json
  # def new
  #   @customer = customer.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @customer }
  #   end
  # end

  # # GET /customers/1/edit
  # def edit
  #   @customer = customer.find(params[:id])
  # end


  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(customer_params)
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /customers/1
  # # DELETE /customers/1.json
  # def destroy
  #   @customer = customer.find(params[:id])
  #   @customer.destroy

  #   respond_to do |format|
  #     format.html { redirect_to customers_url }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def customer_params
      params.require(:customer).permit(:name, :mobile, :show_room_id, :id_type, :id_number, :city, :address, :pin)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for(customer, html: {class: "form-horizontal form-label-left"}) do |f| %>

          <% if customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

              <ul>
                <% customer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Name <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
             <%= f.text_field :name, class: "form-control col-md-7 col-xs-12" %>
              
            </div>
          </div>
          <%= f.hidden_field :show_room_id,value: current_user.show_room_id %>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Mobile <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :mobile, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">ID TYPE <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :id_type, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">ID NUMBER <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :id_number, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">CITY <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :city, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">ADDRESS <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_area :address, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">PIN CODE <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :pin, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= f.submit "Save", class: "btn btn-primary",, disable_with: "Please wait" %>
            </div>
          </div>

       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Customers List - <%= current_user.show_room.name %></h2>  </h2>   <%= link_to 'New Sale', new_customer_path, class: "pull-right btn btn-default" %>
<div class="row">
      <div class="x_content">
        <div class="table-responsive">
          <table class="table table-striped jambo_table bulk_action">
            <thead>
              <tr class="headings">
                <th  class="column-title">Name</th>
                <th class="column-title">Mobile</th>
                <th class="column-title">Show room</th>
                <th class="column-title">Id type</th>
                <th class="column-title">Id number</th>
                <th class="column-title">City</th>
                <th class="column-title">Address</th>
                <th class="column-title">Pin</th>
                <th colspan="3" class="column-title">Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @customers.each do |customer| %>
                <tr class="even_pointer">
                  <td><%= customer.name %></td>
                  <td><%= customer.mobile %></td>
                  <td><%= customer.show_room.name %></td>
                  <td><%= customer.id_type %></td>
                  <td><%= customer.id_number %></td>
                  <td><%= customer.city %></td>
                  <td><%= customer.address %></td>
                  <td><%= customer.pin %></td>
                  <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
                  <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>


      </div>
    </div>
  </div>


</div>

app/views/customers/new.html.erb
<h1>Create Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @customer.mobile %>
</p>

<p>
  <strong>Show room:</strong>
  <%= @customer.show_room %>
</p>

<p>
  <strong>Id type:</strong>
  <%= @customer.id_type %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @customer.id_number %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @customer.pin %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>