config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :sales
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static#index"
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                :integer          not null, primary key
#  chasis_no         :string
#  bike_id           :integer
#  customer_id       :integer
#  payment_type_id   :integer
#  sales_type        :integer
#  discount          :float
#  received_amount   :float
#  diffrence         :string
#  delivery_location :string
#  show_room_id      :integer
#  executive_name    :string
#  financed_by       :string
#  notes             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Sale < ApplicationRecord
  belongs_to :bike
  belongs_to :customer
  belongs_to :payment_type
  belongs_to :show_room
  belongs_to :user

  #sales type 1- OWN , 2. Co dealer
end

app/controllers/sales_controller.rb
class SalesController < InheritedResources::Base
	before_action :authenticate_user!

	def index
		@sales = Sale.where(show_room_id: current_user.show_room_id)

		respond_to do |format|
		  format.html 
		  format.json { render json: @sales }
		end
	end

	def create
	    @sale = Sale.new(sale_params)

	    respond_to do |format|
	      if @sale.save
	        format.html { redirect_to sales_path, notice: 'sale was successfully created.' }
	        format.json { render json: @sale, status: :created, location: @sale }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @sale.errors, status: :unprocessable_entity }
	      end
	    end
  	end

  
  	def update
	    @sale = Sale.find(params[:id])

	    respond_to do |format|
	      if @sale.update_attributes(sale_params)
	        format.html { redirect_to sales_path, notice: 'sale was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @sale.errors, status: :unprocessable_entity }
	      end
	    end
  	end

    private

    def sale_params
      params.require(:sale).permit(:chasis_no, :bike_id, :user_id,:sale_id, :payment_type_id, :sales_type, :discount, :received_amount, :diffrence, :delivery_location, :show_room_id, :executive_name, :financed_by, :notes)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for(sale, html: {class: "form-horizontal form-label-left"}) do |f| %>

         <% if sale.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

              <ul>
                <% sale.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Chasis Number <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
             <%= f.text_field :chasis_no, class: "form-control col-md-7 col-xs-12" %>
              
            </div>
          </div>
          <%= f.hidden_field :show_room_id,value: current_user.show_room_id %>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Bike Model <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.select :bike_id,options_for_select(Bike.all.map {|b| [b.model,b.id]}, sale.bike_id), {:prompt => 'Select bike'},{:class => 'form-control col-md-7 col-xs-12' , required: true } %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Customer <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.select :customer_id,options_for_select(Customer.all.where(show_room_id: current_user.show_room_id).map {|c| [c.name,c.id]}, sale.customer_id), {:prompt => 'Select Customer'},{:class => 'form-control col-md-7 col-xs-12' , required: true } %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Payment Type<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.select :payment_type_id,options_for_select(PaymentType.all.map {|p| [p.name,p.id]}, sale.payment_type_id), {:prompt => 'Select Payment Type'},{:class => 'form-control col-md-7 col-xs-12' , required: true } %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Sales Type <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.select :sales_type,options_for_select([["OWN",1],["Co Dealer",2]]), {:prompt => 'Select Sales Type'},{:class => 'form-control col-md-7 col-xs-12' , required: true } %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Discount <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
               <%= f.number_field :discount, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Received Amount <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.number_field :received_amount, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Diffrence<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :diffrence, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Delivery Location<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :delivery_location, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>

           <%= f.hidden_field :show_room_id,value: current_user.show_room_id %>

           <%= f.hidden_field :user_id,value: current_user.id %>

          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Executive Name<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :executive_name, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Financed By<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :financed_by, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>

           <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Notes<span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_area :notes, class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>


          
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= f.submit "Save", class: "btn btn-primary", disable_with: "Please wait" %>
            </div>
          </div>

       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Sales List - <%= current_user.show_room.name %></h2> <%= link_to 'New Sale', new_sale_path, class: "pull-right btn btn-default" %>
<div class="row">
      <div class="x_content">
        <div class="table-responsive">
          <table class="table table-striped jambo_table bulk_action">
            <thead>
              <tr class="headings">
                <th class="column-title">Chasis no</th>
                <th class="column-title">Bike</th>
                <th class="column-title">Customer</th>
                <th class="column-title">Payment type</th>
                <th class="column-title">Sales type</th>
                <th class="column-title">Discount</th>
                <th class="column-title">Received amount</th>
                <th class="column-title">Diffrence</th>
                <th class="column-title">Delivery location</th>
                <th class="column-title">Show room</th>
                <th class="column-title">Executive name</th>
                <th class="column-title">Financed by</th>
                <th class="column-title">Notes</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @sales.each do |sale| %>
                <tr class="even_pointer">
                  <td><%= sale.chasis_no %></td>
                  <td><%= sale.bike.model %></td>
                  <td><%= sale.customer.name %></td>
                  <td><%= sale.payment_type.name %></td>
                  <td><%= sale.sales_type == 1 ? "OWN" : "Co Dealer" %></td>
                  <td><%= sale.discount.round(0) %></td>
                  <td><%= sale.received_amount.round(0) %></td>
                  <td><%= sale.diffrence.round(0) %></td>
                  <td><%= sale.delivery_location %></td>
                  <td><%= sale.show_room.name %></td>
                  <td><%= sale.executive_name %></td>
                  <td><%= sale.financed_by %></td>
                  <td><%= sale.notes %></td>
                  <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
                  <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>


      </div>
    </div>
  </div>


</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chasis no:</strong>
  <%= @sale.chasis_no %>
</p>

<p>
  <strong>Bike:</strong>
  <%= @sale.bike %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @sale.payment_type %>
</p>

<p>
  <strong>Sales type:</strong>
  <%= @sale.sales_type %>
</p>

<p>
  <strong>Dsicount:</strong>
  <%= @sale.dsicount %>
</p>

<p>
  <strong>Received amount:</strong>
  <%= @sale.received_amount %>
</p>

<p>
  <strong>Diffrence:</strong>
  <%= @sale.diffrence %>
</p>

<p>
  <strong>Delivery location:</strong>
  <%= @sale.delivery_location %>
</p>

<p>
  <strong>Show room:</strong>
  <%= @sale.show_room %>
</p>

<p>
  <strong>Executive name:</strong>
  <%= @sale.executive_name %>
</p>

<p>
  <strong>Financed by:</strong>
  <%= @sale.financed_by %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @sale.notes %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>